//Testing user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "userId": "550e8400-e29b-41d4-a716-446655440000",
  "sectorCode": "12",
  "points": 15
}

### Test 2: Add More Points
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "userId": "550e8400-e29b-41d4-a716-446655440000",
  "sectorCode": "12", 
  "points": 200
}